Added convertkit subscription conponent
TwoStoryRobot/twostoryrobot.com pull request #137
Opened 2020-09-25 03:42 UTC by okanji

2020-09-28 18:16 UTC, calebissharp requested changes
It looks like the form doesn't quite fit on mobile displays:

![image](https://user-images.githubusercontent.com/8854811/94470106-09633080-017c-11eb-9963-57e010fd60f0.png)

2020-10-05 19:53 UTC, okanji commented on src/components/NewsLetter.js
> +          error={status === 'ERROR' || validateInput(email)}
Agreed

2020-10-05 19:56 UTC, okanji commented
@calebissharp I have made the changes per your review, thanks for pointing those things out. I have tested the app using a test deployment with Vercel. For some reason it only works when the convertkit ID is hardcoded, when I set it as an env variable it does not seem to work even though I have set the env variable in the vercel deployment. I am not sure how to test this further, maybe its just an issue with vercel but will work in our production environment?

2020-10-05 20:02 UTC, calebissharp commented
@okanji I think the env var has to be set at build time, if that has anything to do with it.

2020-10-06 19:29 UTC, okanji commented
@calebissharp ok I see, so this should work in production?

2020-10-06 19:37 UTC, calebissharp commented
@okanji IIRC we use semaphore to run the build and then upload it to S3. So you will have to add the environment variables inside semaphore.

2020-10-08 18:15 UTC, merged